# Backend 是 nginx 的内部标识符，用于命名以下特定的 upstream
upstream HotelService {
    # hello 是 Kubernetes 中的后端服务所使用的内部 DNS 名称
    server backend:8080;
}

upstream LocationService{
    server backend:8081;
}

upstream OrderService{
    server backend:8082;
}

upstream TrainService{
    server backend:8083;
}

upstream UserService{
    server backend:8084;
}

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location ^~/hotel-service-api-8080/ {
        proxy_pass  http://HotelService/;
    }

    location ^~/location-service-api-8081/ {
        proxy_pass http://LocationService/;
    }

    location ^~/order-service-api-8082/ {
        proxy_pass http://OrderService/;
    }
    location ^~/train-service-api-8083/ {
        proxy_pass http://TrainService/;
    }

    location ^~/user-service-api-8084/ {
        proxy_pass http://UserService/;
    }
    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # 类似于devServer中的代理.
    


    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

