server.port=8082

management.endpoints.web.exposure.include=*

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=com.dofinal.RG.mybatis.entity

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/hava

spring.web.resources.static-locations=/upload/

### database ###
database.mode = database
database.url = jdbc:mysql://${database.mode}:3306/order_service
database.username = root
database.password = 123456
spring.datasource.url=${database.url}
spring.datasource.username=${database.username}
spring.datasource.password=${database.password}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=order-service
spring.profiles.active=native

### backend ###
backend.mode = backend
backend.hotel.url = http://${backend.mode}:8080
backend.location.url = http://${backend.mode}:8081
backend.order.url = http://${backend.mode}:8082
backend.train.url = http://${backend.mode}:8083
backend.user.url = http://${backend.mode}:8084

### nacos ###
spring.cloud.nacos.config.enabled=false
spring.cloud.nacos.discovery.enabled=false
spring.cloud.nacos.config.refresh-enabled=false
spring.cloud.nacos.discovery.register-enabled=false

logging.file.name=log/log.log
logging.level.root=info